export * from './cellsActions';
export * from './currentTetrominoActions';
export * from './gameEngineActions';
export * from './gameActions';
export * from './playerActions';
export * from './opponentActions';

export const CONSTANTS = {
    CLEAR_CELLS: 'CLEAR_CELLS',
    CLEAR_ROWS: 'CLEAR_ROWS',
    REMOVE_FIRST_ROW: 'REMOVE_FIRST_ROW',
    ADD_TRASH_ROW: 'ADD_TRASH_ROW',
    SET_CURRENT_TETROMINO: 'SET_CURRENT_TETROMINO',
    REFRESH_TETROMINO: 'REFRESH_TETROMINO',
    REFRESHED: 'REFRESHED',
    MERGE_TETROMINO: 'MERGE_TETROMINO',
    CHANGE_GAME_LOOP_ACTIVATION_STATUS: 'CHANGE_GAME_LOOP_ACTIVATION_STATUS',
    CHANGE_GAME_VERIFIER_ACTIVATION_STATUS: 'CHANGE_GAME_VERIFIER_ACTIVATION_STATUS',
    INCREASE_SCORE: 'INCREASE_SCORE',
    INCREASE_SPEED: 'INCREASE_SPEED',
    SET_GAME_OVER: 'SET_GAME_OVER',
    RESET_SCORE: 'RESET_SCORE',
    RESET_SPEED: 'RESET_SPEED',
    INCREASE_POWER: 'INCREASE_POWER',
    DECREASE_POWER: 'DECREASE_POWER',
    RESET_POWER: 'RESET_POWER',
    SET_PLAYER_WIN: 'SET_PLAYER_WIN',
    SET_PLAYER_IN_SEARCH: 'SET_PLAYER_IN_SEARCH',
    CONNECT_PLAYER_TO_SERVER: 'CONNECT_PLAYER_TO_SERVER',
    DISCONNECT_PLAYER_FROM_SERVER: 'DISCONNECT_PLAYER_FROM_SERVER',
    SET_OPPONENT: 'SET_OPPONENT',
    REMOVE_OPPONENT: 'REMOVE_OPPONENT',
    ADD_INPUT_ATTACK: 'ADD_INPUT_ATTACK',
    CLEAR_INPUT_ATTACKS: 'CLEAR_INPUT_ATTACKS'
}
