export * from './cellsActions';
export * from './currentTetrominoActions';
export * from './gameEngineActions';
export * from './gameActions';

export const CONSTANTS = {
    CLEAR_CELLS: 'CLEAR_CELLS',
    CLEAR_ROWS: 'CLEAR_ROWS',
    ADD_TRASH_ROW: 'ADD_TRASH_ROW',
    SET_CURRENT_TETROMINO: 'SET_CURRENT_TETROMINO',
    REFRESH_TETROMINO: 'REFRESH_TETROMINO',
    MERGE_TETROMINO: 'MERGE_TETROMINO',
    CHANGE_GAME_LOOP_ACTIVATION_STATUS: 'CHANGE_GAME_LOOP_ACTIVATION_STATUS',
    CHANGE_GAME_VERIFIER_ACTIVATION_STATUS: 'CHANGE_GAME_VERIFIER_ACTIVATION_STATUS',
    INCREASE_SCORE: 'INCREASE_SCORE',
    INCREASE_SPEED: 'INCREASE_SPEED',
    SET_GAME_OVER: 'SET_GAME_OVER',
    RESET_SCORE: 'RESET_SCORE',
    RESET_SPEED: 'RESET_SPEED',
    INCREASE_POWER: 'INCREASE_POWER',
    DECREASE_POWER: 'DECREASE_POWER'
}
